[package]
name = "cl-total-rdga"
version = "0.1.0"
edition = "2021"
authors = ["Heric da Silva Cruz <hericsilvaho@gmail.com>"]
license = "MIT"

[dependencies]
log = "0.4.25"
petgraph = "0.7.1"
rand = "0.8.5"
env_logger = "0.11"
rayon = "1.10"
num_cpus = "1.16.0"
chrono = "0.4"
